### ISSUE TITLE
Latest forge version (1.0.3) doesn't work with the new Oculus 1.7.0 because of version range in mod .jar

### ISSUE THREAD

**Issue by Tapacywka** [DoonGuy/Bad-Horse-Fix#5]

**Comment by DoonGuy** [comment]
Thank you for pointing this out, I somehow didn't see that Oculus got the 1.7.0 update. I'll start working on the fix soon and will probably have an update out later today.

**Comment by DoonGuy** [comment]
v2.0.0, which fixes this, is now out on [GitHub](https://github.com/DoonGuy/Bad-Horse-Fix/releases/tag/v2.0.0), [Modrinth](https://modrinth.com/mod/bad-horse-fix/version/2.0.0-forge), and soon on CurseForge.
